# Generated by Django 3.0.5 on 2020-04-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movrotativo',
            name='now',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
