# Generated by Django 3.0.5 on 2020-04-26 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mensalista'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovMensalista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_pgto', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pago', models.BooleanField(default=False)),
                ('mensalista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Mensalista')),
            ],
        ),
    ]
